### ISSUE TITLE
module 'msspeak' has no attribute 'MSSpeak'

### ISSUE THREAD

**Issue by lardconcepts** [newfies-dialer/python-msspeak#1]
EDIT: Just about to give up after 4 hours when I found this:
https://groups.google.com/d/msg/newfies-dialer/SAqkdInNnpk/2mc1avCODAAJ

Hi there, and thanks for this library, but I'm struggling a bit.

My python knowledge is fairly limited, but I want to use this on the current version of python 3.6, so I corrected the print function in the example, ran 2to3 on msspeak.py and checked everything with pyflakes and it all passed.

In addition, I have made the changes to test that the standalone file example works. See https://github.com/lardconcepts/python-msspeak/blob/master/msspeak/msspeak.py

But  for this example code:
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#https://github.com/newfies-dialer/python-msspeak

import msspeak
subscription_key = 'XXXXXXXXXXXXXXXXXX'
tts_msspeak = msspeak.MSSpeak(subscription_key, '/tmp/')
output_filename = tts_msspeak.speak("This is the text I will speak to you", "en-GB")
print ("Recorded TTS to %s" % output_filename)

```

I get

```
Traceback (most recent call last):
  File "mstts.py", line 11, in <module>
    tts_msspeak = msspeak.MSSpeak(subscription_key, '/tmp/')
AttributeError: module 'msspeak' has no attribute 'MSSpeak'
```

 I can quite clearly see class `MSSpeak(object): `defined at https://github.com/newfies-dialer/python-msspeak/blob/master/msspeak/msspeak.py#L190 so, any advice is appreciated.

Any advice would be appreciated.

**Comment by areski** [comment]
closing as it's fixed by the merged PR
